export const plan = [
  {
    week: 1,
    theme: "Binary Search + Monotonic Stack/Queue + Greedy Foundations",
    days: [
      {
        day: 1,
        pattern: "Binary Search on Sorted Arrays",
        problems: [
          { name: "Search in Rotated Sorted Array", diff: "Medium", lc: "33" },
          { name: "Find Minimum in Rotated Sorted Array", diff: "Medium", lc: "153" },
          { name: "Koko Eating Bananas (Search on Answer)", diff: "Medium", lc: "875" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "OOPs: 4 pillars, abstraction vs encapsulation (deep dive)",
        spaced: null,
        isMock: false,
      },
      {
        day: 2,
        pattern: "Binary Search on Answer (Advanced)",
        problems: [
          { name: "Capacity to Ship Packages Within D Days", diff: "Medium", lc: "1011" },
          { name: "Median of Two Sorted Arrays", diff: "Hard", lc: "4" },
          { name: "Aggressive Cows / Allocate Books (GFG)", diff: "Hard", lc: "GFG" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "Behavioral: Draft STAR answer for 'Tell me about yourself'",
        spaced: null,
        isMock: false,
      },
      {
        day: 3,
        pattern: "REVISION DAY — Binary Search Family",
        problems: [
          { name: "Re-solve: Search in Rotated (no hints)", diff: "Medium", lc: "33" },
          { name: "Re-solve: Median of Two Sorted Arrays", diff: "Hard", lc: "4" },
          { name: "Review spaced repetition log", diff: "—", lc: null },
        ],
        timeSplit: "2h Revision | 1.5h New Reading | 1h CS | 30m Log",
        nonDsa: "OOPs: SOLID principles with code examples",
        spaced: "Log Day 1 & 2 problems for Day+7 revisit",
        isMock: false,
        isRevision: true,
      },
      {
        day: 4,
        pattern: "Monotonic Stack — Next Greater/Smaller Family",
        problems: [
          { name: "Daily Temperatures", diff: "Medium", lc: "739" },
          { name: "Largest Rectangle in Histogram", diff: "Hard", lc: "84" },
          { name: "Trapping Rain Water", diff: "Hard", lc: "42" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "OS: Process vs Thread, context switching",
        spaced: null,
        isMock: false,
      },
      {
        day: 5,
        pattern: "Sliding Window + Monotonic Deque",
        problems: [
          { name: "Sliding Window Maximum", diff: "Hard", lc: "239" },
          { name: "Longest Subarray with at most K Distinct Chars", diff: "Medium", lc: "340" },
          { name: "Minimum Window Substring", diff: "Hard", lc: "76" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "Resume: Deep-dive Project #1 — explain design decisions",
        spaced: "Revisit Day 1 problems (Day+4 gap)",
        isMock: false,
      },
      {
        day: 6,
        pattern: "Greedy — Interval + Scheduling Problems",
        problems: [
          { name: "Non-overlapping Intervals", diff: "Medium", lc: "435" },
          { name: "Jump Game II", diff: "Medium", lc: "45" },
          { name: "Minimum Number of Arrows to Burst Balloons", diff: "Medium", lc: "452" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "DBMS: Normalization (1NF–3NF), ACID properties",
        spaced: null,
        isMock: false,
      },
      {
        day: 7,
        pattern: "MOCK INTERVIEW DAY",
        problems: [
          { name: "Timed: 2 unseen Medium problems (45 min each)", diff: "Medium", lc: null },
          { name: "Verbal walkthrough + complexity analysis", diff: "—", lc: null },
          { name: "Week 1 weak-area audit", diff: "—", lc: null },
        ],
        timeSplit: "2h Mock | 2h Weak Area Fix | 1h Behavioral | 30m Plan Week 2",
        nonDsa: "HR: 'Strengths & Weaknesses' STAR prep",
        spaced: "Flag topics <70% confidence for Week 2 reinforcement",
        isMock: true,
      },
    ],
  },
  {
    week: 2,
    theme: "Heaps + Prefix Sum + Bit Manipulation",
    days: [
      {
        day: 1,
        pattern: "Heap / Priority Queue — Top-K Family",
        problems: [
          { name: "Kth Largest Element in Array", diff: "Medium", lc: "215" },
          { name: "Top K Frequent Elements", diff: "Medium", lc: "347" },
          { name: "Find Median from Data Stream", diff: "Hard", lc: "295" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "OOPs: Design Patterns — Singleton, Factory, Observer",
        spaced: "Revisit Week 1 Day 1 problems",
        isMock: false,
      },
      {
        day: 2,
        pattern: "Heap — Merge K Lists + Task Scheduling",
        problems: [
          { name: "Merge K Sorted Lists", diff: "Hard", lc: "23" },
          { name: "Task Scheduler", diff: "Medium", lc: "621" },
          { name: "K Closest Points to Origin", diff: "Medium", lc: "973" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "OS: Memory management, paging, segmentation",
        spaced: null,
        isMock: false,
      },
      {
        day: 3,
        pattern: "REVISION DAY — Heap + Week 1 Spaced",
        problems: [
          { name: "Re-solve: Find Median from Data Stream", diff: "Hard", lc: "295" },
          { name: "Re-solve: Largest Rectangle in Histogram", diff: "Hard", lc: "84" },
          { name: "Pattern recap: when to use min-heap vs max-heap", diff: "—", lc: null },
        ],
        timeSplit: "2h Revision | 1.5h Concept | 1h CS | 30m Log",
        nonDsa: "LLD: Design a Parking Lot (entities, relationships, classes)",
        spaced: "Log Week 2 D1–D2 for Day+7 revisit",
        isMock: false,
        isRevision: true,
      },
      {
        day: 4,
        pattern: "Prefix Sum + Range Queries",
        problems: [
          { name: "Range Sum Query — Immutable", diff: "Easy→Pattern", lc: "303" },
          { name: "Subarray Sum Equals K", diff: "Medium", lc: "560" },
          { name: "Count of Range Sum", diff: "Hard", lc: "327" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "CN: OSI model, TCP vs UDP, HTTP vs HTTPS",
        spaced: null,
        isMock: false,
      },
      {
        day: 5,
        pattern: "Bit Manipulation — Fundamentals to Advanced",
        problems: [
          { name: "Single Number II (XOR mastery)", diff: "Medium", lc: "137" },
          { name: "Counting Bits", diff: "Easy+", lc: "338" },
          { name: "Maximum XOR of Two Numbers", diff: "Medium", lc: "421" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "Behavioral: 'Conflict with teammate' STAR answer",
        spaced: "Revisit Week 1 Day 4 (Monotonic Stack)",
        isMock: false,
      },
      {
        day: 6,
        pattern: "Bit Manipulation + Greedy Mixed",
        problems: [
          { name: "Divide Two Integers (bit ops)", diff: "Medium", lc: "29" },
          { name: "Minimum Bit Flips to Convert Number", diff: "Easy+", lc: "2220" },
          { name: "Gas Station (Greedy)", diff: "Medium", lc: "134" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "DBMS: Indexes (B-Tree vs Hash), query optimization",
        spaced: null,
        isMock: false,
      },
      {
        day: 7,
        pattern: "MOCK INTERVIEW DAY",
        problems: [
          { name: "Timed: 1 Hard + 1 Medium (unseen)", diff: "Hard/Medium", lc: null },
          { name: "Explain time/space tradeoffs verbally", diff: "—", lc: null },
          { name: "Week 2 weak-area audit", diff: "—", lc: null },
        ],
        timeSplit: "2h Mock | 2h Weak Area | 1h Behavioral | 30m Plan Week 3",
        nonDsa: "HR: 'Leadership/initiative' STAR prep",
        spaced: "Flag weak topics, schedule reinforcement",
        isMock: true,
      },
    ],
  },
  {
    week: 3,
    theme: "Binary Trees + BST + Tree DP",
    days: [
      {
        day: 1,
        pattern: "Binary Tree Traversals + Views",
        problems: [
          { name: "Binary Tree Right Side View", diff: "Medium", lc: "199" },
          { name: "Vertical Order Traversal", diff: "Hard", lc: "987" },
          { name: "Morris Traversal (concept + code)", diff: "Hard", lc: "94" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "OOPs: Inheritance vs Composition, virtual functions",
        spaced: "Revisit Week 2 D1 (Heap) problems",
        isMock: false,
      },
      {
        day: 2,
        pattern: "LCA + Distance in Trees",
        problems: [
          { name: "Lowest Common Ancestor of BST", diff: "Medium", lc: "235" },
          { name: "LCA of Binary Tree", diff: "Medium", lc: "236" },
          { name: "Kth Ancestor of Tree Node", diff: "Hard", lc: "1483" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "LLD: Design a Library Management System",
        spaced: null,
        isMock: false,
      },
      {
        day: 3,
        pattern: "REVISION DAY — Trees",
        problems: [
          { name: "Re-solve: LCA of Binary Tree", diff: "Medium", lc: "236" },
          { name: "Re-solve: Vertical Order Traversal", diff: "Hard", lc: "987" },
          { name: "Pattern: DFS on trees — return value design", diff: "—", lc: null },
        ],
        timeSplit: "2h Revision | 1.5h Concept | 1h CS | 30m Log",
        nonDsa: "OS: Deadlock — conditions, prevention, banker's algorithm",
        spaced: "Log W3D1–D2 for Day+7 revisit",
        isMock: false,
        isRevision: true,
      },
      {
        day: 4,
        pattern: "BST — Validation, Construction, Queries",
        problems: [
          { name: "Validate Binary Search Tree", diff: "Medium", lc: "98" },
          { name: "Recover Binary Search Tree", diff: "Hard", lc: "99" },
          { name: "Kth Smallest in BST (follow-up: stream)", diff: "Medium", lc: "230" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "CN: DNS, CDN, Load Balancing concepts",
        spaced: null,
        isMock: false,
      },
      {
        day: 5,
        pattern: "Tree DP + Diameter/Path Problems",
        problems: [
          { name: "Binary Tree Maximum Path Sum", diff: "Hard", lc: "124" },
          { name: "House Robber III (DP on Tree)", diff: "Medium", lc: "337" },
          { name: "Diameter of Binary Tree", diff: "Easy+", lc: "543" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "Resume: Project #2 deep-dive — scalability decisions",
        spaced: "Revisit Week 2 D4 (Prefix Sum)",
        isMock: false,
      },
      {
        day: 6,
        pattern: "Serialization + Trie (Tree cousin)",
        problems: [
          { name: "Serialize and Deserialize Binary Tree", diff: "Hard", lc: "297" },
          { name: "Implement Trie", diff: "Medium", lc: "208" },
          { name: "Word Search II (Trie + Backtrack)", diff: "Hard", lc: "212" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "DBMS: Transactions, isolation levels, deadlock in DB",
        spaced: null,
        isMock: false,
      },
      {
        day: 7,
        pattern: "OA SIMULATION DAY #1",
        problems: [
          { name: "Full 90-min OA: 3 problems, timed, no hints", diff: "Mixed", lc: null },
          { name: "Post-OA: analyze each problem approach", diff: "—", lc: null },
          { name: "Week 3 weak-area audit", diff: "—", lc: null },
        ],
        timeSplit: "90m OA | 1.5h Analysis | 1.5h Weak Areas | 1h Behavioral",
        nonDsa: "HR: 'Failure/what you learned' STAR prep",
        spaced: "Full spaced repetition audit for Weeks 1–3",
        isMock: true,
        isOA: true,
      },
    ],
  },
  {
    week: 4,
    theme: "Graphs — BFS/DFS/Topological Sort/DSU",
    days: [
      {
        day: 1,
        pattern: "Graph BFS — Multi-source, Shortest Path",
        problems: [
          { name: "Rotting Oranges", diff: "Medium", lc: "994" },
          { name: "Word Ladder", diff: "Hard", lc: "127" },
          { name: "01 Matrix", diff: "Medium", lc: "542" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "OOPs: Abstract class vs Interface, polymorphism deep dive",
        spaced: "Revisit W3D1 (Tree Traversal)",
        isMock: false,
      },
      {
        day: 2,
        pattern: "Graph DFS — Connected Components, Cycle Detection",
        problems: [
          { name: "Number of Islands", diff: "Medium", lc: "200" },
          { name: "Course Schedule (Cycle in Directed Graph)", diff: "Medium", lc: "207" },
          { name: "Pacific Atlantic Water Flow", diff: "Medium", lc: "417" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "LLD: Design an Elevator System",
        spaced: null,
        isMock: false,
      },
      {
        day: 3,
        pattern: "REVISION DAY — Graphs Phase 1",
        problems: [
          { name: "Re-solve: Word Ladder", diff: "Hard", lc: "127" },
          { name: "Re-solve: Course Schedule", diff: "Medium", lc: "207" },
          { name: "Pattern: BFS vs DFS decision framework", diff: "—", lc: null },
        ],
        timeSplit: "2h Revision | 1.5h Concept | 1h CS | 30m Log",
        nonDsa: "OS: File systems, inode, virtual memory",
        spaced: "Log W4D1–D2 for Day+7 revisit",
        isMock: false,
        isRevision: true,
      },
      {
        day: 4,
        pattern: "Topological Sort — Kahn's + DFS-based",
        problems: [
          { name: "Course Schedule II", diff: "Medium", lc: "210" },
          { name: "Alien Dictionary", diff: "Hard", lc: "269" },
          { name: "Largest Color Value in DAG", diff: "Hard", lc: "1857" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "CN: Sockets, TCP handshake, HTTP/2 vs HTTP/3",
        spaced: null,
        isMock: false,
      },
      {
        day: 5,
        pattern: "Disjoint Set Union (DSU/Union-Find)",
        problems: [
          { name: "Number of Provinces (DSU)", diff: "Medium", lc: "547" },
          { name: "Accounts Merge", diff: "Medium", lc: "721" },
          { name: "Redundant Connection", diff: "Medium", lc: "684" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "Behavioral: 'Tight deadline / pressure' STAR prep",
        spaced: "Revisit W3D5 (Tree DP)",
        isMock: false,
      },
      {
        day: 6,
        pattern: "Shortest Path — Dijkstra + Bellman-Ford",
        problems: [
          { name: "Network Delay Time (Dijkstra)", diff: "Medium", lc: "743" },
          { name: "Cheapest Flights K Stops (Bellman-Ford)", diff: "Medium", lc: "787" },
          { name: "Path with Minimum Effort", diff: "Medium", lc: "1631" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "DBMS: SQL joins, window functions, explain plan",
        spaced: null,
        isMock: false,
      },
      {
        day: 7,
        pattern: "MOCK INTERVIEW DAY",
        problems: [
          { name: "Timed: Graph Hard problem (unseen, 45 min)", diff: "Hard", lc: null },
          { name: "Timed: Tree Medium (verbal explanation)", diff: "Medium", lc: null },
          { name: "Week 4 weak-area audit", diff: "—", lc: null },
        ],
        timeSplit: "2h Mock | 2h Weak Area | 1h Behavioral | 30m Plan Week 5",
        nonDsa: "HR: 'Why this company?' prep (customize per company)",
        spaced: "Full Weeks 1–4 spaced repetition check",
        isMock: true,
      },
    ],
  },
  {
    week: 5,
    theme: "Dynamic Programming — 1D + 2D + Subsequences",
    days: [
      {
        day: 1,
        pattern: "1D DP — Classic Patterns",
        problems: [
          { name: "House Robber (1D DP baseline)", diff: "Medium", lc: "198" },
          { name: "Decode Ways", diff: "Medium", lc: "91" },
          { name: "Longest Increasing Subsequence (O(n log n))", diff: "Medium", lc: "300" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "HLD Intro: Monolith vs Microservices, when to split",
        spaced: "Revisit W4D1 (BFS problems)",
        isMock: false,
      },
      {
        day: 2,
        pattern: "2D DP — Grid Problems",
        problems: [
          { name: "Unique Paths II", diff: "Medium", lc: "63" },
          { name: "Minimum Path Sum", diff: "Medium", lc: "64" },
          { name: "Dungeon Game", diff: "Hard", lc: "174" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "HLD: Design URL Shortener (entities, DB, caching)",
        spaced: null,
        isMock: false,
      },
      {
        day: 3,
        pattern: "REVISION DAY — DP Phase 1",
        problems: [
          { name: "Re-solve: LIS O(n log n)", diff: "Medium", lc: "300" },
          { name: "Re-solve: Dungeon Game", diff: "Hard", lc: "174" },
          { name: "Pattern: Tabulation vs Memoization tradeoffs", diff: "—", lc: null },
        ],
        timeSplit: "2h Revision | 1.5h Concept | 1h CS | 30m Log",
        nonDsa: "OS: Scheduling algorithms — FCFS, SJF, Round Robin",
        spaced: "Log W5D1–D2 for Day+7 revisit",
        isMock: false,
        isRevision: true,
      },
      {
        day: 4,
        pattern: "DP — Subsequences (LCS Family)",
        problems: [
          { name: "Longest Common Subsequence", diff: "Medium", lc: "1143" },
          { name: "Edit Distance", diff: "Hard", lc: "72" },
          { name: "Distinct Subsequences", diff: "Hard", lc: "115" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "CN: REST vs GraphQL, API design principles",
        spaced: null,
        isMock: false,
      },
      {
        day: 5,
        pattern: "Partition DP — Palindromes + Knapsack",
        problems: [
          { name: "Palindrome Partitioning II", diff: "Hard", lc: "132" },
          { name: "0/1 Knapsack (GFG + variations)", diff: "Medium", lc: "GFG" },
          { name: "Partition Equal Subset Sum", diff: "Medium", lc: "416" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "Resume: Project #3 — failure/what you'd do differently",
        spaced: "Revisit W4D4 (Topological Sort)",
        isMock: false,
      },
      {
        day: 6,
        pattern: "DP — Stocks + State Machine DP",
        problems: [
          { name: "Best Time to Buy and Sell Stock III", diff: "Hard", lc: "123" },
          { name: "Best Time to Buy and Sell Stock with Cooldown", diff: "Medium", lc: "309" },
          { name: "Best Time to Buy and Sell Stock IV", diff: "Hard", lc: "188" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "DBMS: Stored procedures, triggers, views",
        spaced: null,
        isMock: false,
      },
      {
        day: 7,
        pattern: "MOCK INTERVIEW DAY",
        problems: [
          { name: "Timed: DP Hard unseen (45 min)", diff: "Hard", lc: null },
          { name: "Timed: Mixed topic Medium (verbal)", diff: "Medium", lc: null },
          { name: "Week 5 weak-area audit", diff: "—", lc: null },
        ],
        timeSplit: "2h Mock | 2h Weak Area | 1h Behavioral | 30m Plan Week 6",
        nonDsa: "HR: 'Where do you see yourself in 5 years?'",
        spaced: "Spaced repetition audit Weeks 1–5",
        isMock: true,
      },
    ],
  },
  {
    week: 6,
    theme: "DP Advanced + Graphs Advanced (MST, Floyd-Warshall)",
    days: [
      {
        day: 1,
        pattern: "Interval DP + Matrix Chain",
        problems: [
          { name: "Burst Balloons", diff: "Hard", lc: "312" },
          { name: "Strange Printer", diff: "Hard", lc: "664" },
          { name: "Zuma Game", diff: "Hard", lc: "488" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "HLD: Design Twitter/Instagram feed (fan-out, caching)",
        spaced: "Revisit W5D1 (1D DP)",
        isMock: false,
      },
      {
        day: 2,
        pattern: "MST — Kruskal + Prim + Applications",
        problems: [
          { name: "Min Cost to Connect All Points (Prim's)", diff: "Medium", lc: "1584" },
          { name: "Optimize Water Distribution (Kruskal)", diff: "Hard", lc: "1168" },
          { name: "Find Critical / Pseudo-Critical Edges", diff: "Hard", lc: "1489" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "LLD: Design a Rate Limiter",
        spaced: null,
        isMock: false,
      },
      {
        day: 3,
        pattern: "REVISION DAY — Adv DP + Graph",
        problems: [
          { name: "Re-solve: Burst Balloons", diff: "Hard", lc: "312" },
          { name: "Re-solve: Min Cost to Connect Points", diff: "Medium", lc: "1584" },
          { name: "Pattern: Interval DP identification tips", diff: "—", lc: null },
        ],
        timeSplit: "2h Revision | 1.5h Concept | 1h CS | 30m Log",
        nonDsa: "OS: Synchronization — mutex, semaphore, monitor",
        spaced: "Log W6D1–D2 for Day+7 revisit",
        isMock: false,
        isRevision: true,
      },
      {
        day: 4,
        pattern: "Floyd-Warshall + Johnson's + All-Pairs SP",
        problems: [
          { name: "Find the City With Smallest Neighbors (Floyd)", diff: "Medium", lc: "1334" },
          { name: "Evaluate Division (Graph modeling)", diff: "Medium", lc: "399" },
          { name: "Reachable Nodes in Graph (Dijkstra variant)", diff: "Hard", lc: "882" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "CN: Consistent hashing, sharding strategies",
        spaced: null,
        isMock: false,
      },
      {
        day: 5,
        pattern: "DP on Graphs + Bitmask DP",
        problems: [
          { name: "Shortest Path Visiting All Nodes (Bitmask BFS)", diff: "Hard", lc: "847" },
          { name: "Minimum Cost to Reach Destination (DP+Graph)", diff: "Hard", lc: "787" },
          { name: "Count Ways to Build Good String", diff: "Medium", lc: "2466" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "Behavioral: 'Biggest technical challenge' STAR prep",
        spaced: "Revisit W5D4 (LCS family)",
        isMock: false,
      },
      {
        day: 6,
        pattern: "Advanced Strings — Z-algo, KMP, Rabin-Karp",
        problems: [
          { name: "Find All Anagrams (sliding window)", diff: "Medium", lc: "438" },
          { name: "Shortest Palindrome (KMP)", diff: "Hard", lc: "214" },
          { name: "Longest Duplicate Substring (Rolling Hash)", diff: "Hard", lc: "1044" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "DBMS: Query planning, partitioning, sharding in DB",
        spaced: null,
        isMock: false,
      },
      {
        day: 7,
        pattern: "OA SIMULATION DAY #2",
        problems: [
          { name: "Full 90-min OA: 3 problems, timed, no hints", diff: "Mixed", lc: null },
          { name: "Post-OA deep analysis", diff: "—", lc: null },
          { name: "Week 6 audit + plan final 2 weeks", diff: "—", lc: null },
        ],
        timeSplit: "90m OA | 1.5h Analysis | 1.5h Weak Areas | 1h HLD",
        nonDsa: "HLD: Design WhatsApp (messaging, presence, media)",
        spaced: "Full Weeks 1–6 spaced repetition audit",
        isMock: true,
        isOA: true,
      },
    ],
  },
  {
    week: 7,
    theme: "Segment Tree + Fenwick Tree + Advanced Data Structures",
    days: [
      {
        day: 1,
        pattern: "Fenwick Tree (BIT) — Point Update, Range Query",
        problems: [
          { name: "Range Sum Query — Mutable (BIT)", diff: "Medium", lc: "307" },
          { name: "Count of Smaller Numbers After Self", diff: "Hard", lc: "315" },
          { name: "Reverse Pairs (BIT + merge sort)", diff: "Hard", lc: "493" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "HLD: Design a Search Engine (indexing, ranking)",
        spaced: "Revisit W6D1 (Interval DP)",
        isMock: false,
      },
      {
        day: 2,
        pattern: "Segment Tree — Range Min/Max/Sum + Lazy Propagation",
        problems: [
          { name: "Segment Tree Build + Query (template)", diff: "Hard", lc: "307" },
          { name: "Range Sum with Lazy Propagation (GFG)", diff: "Hard", lc: "GFG" },
          { name: "My Calendar III (Segment Tree)", diff: "Hard", lc: "732" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "LLD: Design a Cache (LRU + LFU implementations)",
        spaced: null,
        isMock: false,
      },
      {
        day: 3,
        pattern: "REVISION DAY — Advanced DS",
        problems: [
          { name: "Re-solve: Count Smaller After Self", diff: "Hard", lc: "315" },
          { name: "Re-solve: My Calendar III", diff: "Hard", lc: "732" },
          { name: "Pattern: BIT vs Segment Tree — when to choose", diff: "—", lc: null },
        ],
        timeSplit: "2h Revision | 1.5h Concept | 1h CS | 30m Log",
        nonDsa: "OS: Inter-process communication, pipes, message queues",
        spaced: "Log W7D1–D2 for Day+7 revisit",
        isMock: false,
        isRevision: true,
      },
      {
        day: 4,
        pattern: "Backtracking — Permutations, Combinations, N-Queens",
        problems: [
          { name: "Sudoku Solver", diff: "Hard", lc: "37" },
          { name: "N-Queens II", diff: "Hard", lc: "52" },
          { name: "Palindrome Partitioning (backtrack)", diff: "Medium", lc: "131" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "CN: WebSockets, long polling, SSE — when to use each",
        spaced: null,
        isMock: false,
      },
      {
        day: 5,
        pattern: "Important Linked List Hard Problems",
        problems: [
          { name: "LRU Cache (HashMap + DLL)", diff: "Medium", lc: "146" },
          { name: "Copy List with Random Pointer", diff: "Medium", lc: "138" },
          { name: "Reverse Nodes in K-Group", diff: "Hard", lc: "25" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "Behavioral: 'Most impactful project' STAR prep",
        spaced: "Revisit W6D4 (Floyd-Warshall problems)",
        isMock: false,
      },
      {
        day: 6,
        pattern: "Mixed Hard — Array/Matrix Interview Classics",
        problems: [
          { name: "First Missing Positive", diff: "Hard", lc: "41" },
          { name: "Jump Game VI (DP + Deque)", diff: "Medium", lc: "1696" },
          { name: "Maximal Rectangle", diff: "Hard", lc: "85" },
        ],
        timeSplit: "3h DSA | 1h Revision | 1h CS+Interview | 30m Log",
        nonDsa: "DBMS: CAP theorem, eventual consistency, NoSQL vs SQL",
        spaced: null,
        isMock: false,
      },
      {
        day: 7,
        pattern: "MOCK INTERVIEW DAY",
        problems: [
          { name: "Timed: Segment Tree / BIT problem (unseen)", diff: "Hard", lc: null },
          { name: "Timed: Backtracking Hard", diff: "Hard", lc: null },
          { name: "Week 7 weak-area audit", diff: "—", lc: null },
        ],
        timeSplit: "2h Mock | 2h Weak Area | 1h Behavioral | 30m Plan Week 8",
        nonDsa: "HR: Full mock behavioral interview (record yourself)",
        spaced: "Weeks 1–7 master audit",
        isMock: true,
      },
    ],
  },
  {
    week: 8,
    theme: "Full Integration — Mock Sprints + Gap Filling + Interview Simulation",
    days: [
      {
        day: 1,
        pattern: "Company-Specific Problem Sprint (Amazon focus)",
        problems: [
          { name: "Amazon OA: Top K Frequent (Heap)", diff: "Medium", lc: "347" },
          { name: "Amazon: Number of Islands variant", diff: "Medium", lc: "200" },
          { name: "Amazon: Meeting Rooms II", diff: "Medium", lc: "253" },
        ],
        timeSplit: "2.5h DSA | 1h Revision | 1.5h Interview Prep | 30m Log",
        nonDsa: "Amazon Leadership Principles — map your projects to each LP",
        spaced: "Revisit all flagged weak areas from Weeks 1–7",
        isMock: false,
      },
      {
        day: 2,
        pattern: "Company-Specific Problem Sprint (Google focus)",
        problems: [
          { name: "Google: Trapping Rain Water", diff: "Hard", lc: "42" },
          { name: "Google: Word Break II", diff: "Hard", lc: "140" },
          { name: "Google: Median of Data Stream", diff: "Hard", lc: "295" },
        ],
        timeSplit: "2.5h DSA | 1h Revision | 1.5h Interview Prep | 30m Log",
        nonDsa: "Google: Googleyness + clarity of thought in answers",
        spaced: null,
        isMock: false,
      },
      {
        day: 3,
        pattern: "REVISION DAY — Personal Weak Areas",
        problems: [
          { name: "Re-solve: Your 3 hardest problems (from log)", diff: "Hard", lc: "personal" },
          { name: "Re-solve: 1 DP Hard cold", diff: "Hard", lc: null },
          { name: "Complete pattern cheat sheet", diff: "—", lc: null },
        ],
        timeSplit: "2h Revision | 1.5h Cheat Sheet | 1h CS | 30m Log",
        nonDsa: "HLD: Design Netflix (CDN, encoding, recommendation)",
        spaced: "Final spaced repetition sweep",
        isMock: false,
        isRevision: true,
      },
      {
        day: 4,
        pattern: "Company-Specific Sprint (Microsoft focus)",
        problems: [
          { name: "Microsoft: Serialize/Deserialize Tree", diff: "Hard", lc: "297" },
          { name: "Microsoft: LRU Cache", diff: "Medium", lc: "146" },
          { name: "Microsoft: Alien Dictionary", diff: "Hard", lc: "269" },
        ],
        timeSplit: "2.5h DSA | 1h Revision | 1.5h Interview Prep | 30m Log",
        nonDsa: "CN: Final review — OSI, TCP, CDN, load balancing",
        spaced: null,
        isMock: false,
      },
      {
        day: 5,
        pattern: "Full Mock Interview — SDE-1 Simulation",
        problems: [
          { name: "45-min interview: intro + 2 problems + QnA", diff: "Mixed", lc: null },
          { name: "Full system design: Design a ride-sharing app", diff: "—", lc: null },
          { name: "Behavioral round: full set of STAR answers", diff: "—", lc: null },
        ],
        timeSplit: "2h Tech Interview | 1h System Design | 1.5h Behavioral | 30m Review",
        nonDsa: "Full HR round simulation — record and review",
        spaced: null,
        isMock: true,
      },
      {
        day: 6,
        pattern: "Final Gap Filling + Hardest 5",
        problems: [
          { name: "Re-attempt: Personal hardest unsolved problem", diff: "Hard", lc: "personal" },
          { name: "Cold solve: 1 Hard DP", diff: "Hard", lc: null },
          { name: "Cold solve: 1 Hard Graph", diff: "Hard", lc: null },
        ],
        timeSplit: "3h Cold Solving | 1h Review | 1h Final CS | 30m Mental Prep",
        nonDsa: "DBMS final: All SQL types, joins, window functions speed run",
        spaced: null,
        isMock: false,
      },
      {
        day: 7,
        pattern: "FINAL FULL MOCK + CONSOLIDATION",
        problems: [
          { name: "Final OA Simulation: 90 min, 3 hard problems", diff: "Hard", lc: null },
          { name: "Final system design interview", diff: "—", lc: null },
          { name: "Mindset + interview day checklist", diff: "—", lc: null },
        ],
        timeSplit: "90m OA | 1h HLD | 1h Behavioral | 1.5h Rest + Review",
        nonDsa: "Interview day checklist: what to say, ask, and avoid",
        spaced: "YOU ARE READY. 🎯",
        isMock: true,
        isOA: true,
      },
    ],
  },
];